# touch split-first-dependent.log
jupyter nbconvert --to script *.ipynb


# python3 -u split-first-dependent-main-last.py --model_name LSTM --stim 0 --segment_number 1 --len_reduction None --isdebug False >> split-first-dependent.log
# python3 -u split-first-dependent-main-last.py --model_name LSTM --stim 1 --segment_number 1 --len_reduction None --isdebug False >> split-first-dependent.log
# python3 -u split-first-dependent-main-last.py --model_name LSTM --stim 0 --segment_number 3 --len_reduction None --isdebug False >> split-first-dependent.log
# python3 -u split-first-dependent-main-last.py --model_name LSTM --stim 1 --segment_number 3 --len_reduction None --isdebug False >> split-first-dependent.log
# python3 -u split-first-dependent-main-last.py --model_name LSTM --stim 0 --segment_number 5 --len_reduction None --isdebug False >> split-first-dependent.log
# python3 -u split-first-dependent-main-last.py --model_name LSTM --stim 1 --segment_number 5 --len_reduction None --isdebug False >> split-first-dependent.log
# python3 -u split-first-dependent-main-last.py --model_name LSTM --stim 0 --segment_number 60 --len_reduction None --isdebug False >> split-first-dependent.log
# python3 -u split-first-dependent-main-last.py --model_name LSTM --stim 1 --segment_number 60 --len_reduction None --isdebug False >> split-first-dependent.log
# python3 -u split-first-dependent-main-last.py --model_name Conv1D_LSTM --stim 0 --segment_number 1 --len_reduction None --isdebug False >> split-first-dependent.log
# python3 -u split-first-dependent-main-last.py --model_name Conv1D_LSTM --stim 1 --segment_number 1 --len_reduction None --isdebug False >> split-first-dependent.log
# python3 -u split-first-dependent-main-last.py --model_name Conv1D_LSTM --stim 0 --segment_number 3 --len_reduction None --isdebug False >> split-first-dependent.log
# python3 -u split-first-dependent-main-last.py --model_name Conv1D_LSTM --stim 1 --segment_number 3 --len_reduction None --isdebug False >> split-first-dependent.log
# python3 -u split-first-dependent-main-last.py --model_name Conv1D_LSTM --stim 0 --segment_number 5 --len_reduction None --isdebug False >> split-first-dependent.log
# python3 -u split-first-dependent-main-last.py --model_name Conv1D_LSTM --stim 1 --segment_number 5 --len_reduction None --isdebug False >> split-first-dependent.log
# python3 -u split-first-dependent-main-last.py --model_name Conv1D_LSTM --stim 0 --segment_number 60 --len_reduction None --isdebug False >> split-first-dependent.log
# python3 -u split-first-dependent-main-last.py --model_name Conv1D_LSTM --stim 1 --segment_number 60 --len_reduction None --isdebug False >> split-first-dependent.log
# python3 -u split-first-dependent-main-last.py --model_name Conv1D_LSTM_Attention --stim 0 --segment_number 1 --len_reduction None --isdebug False >> split-first-dependent.log
# python3 -u split-first-dependent-main-last.py --model_name Conv1D_LSTM_Attention --stim 1 --segment_number 1 --len_reduction None --isdebug False >> split-first-dependent.log
# python3 -u split-first-dependent-main-last.py --model_name Conv1D_LSTM_Attention --stim 0 --segment_number 3 --len_reduction None --isdebug False >> split-first-dependent.log
# python3 -u split-first-dependent-main-last.py --model_name Conv1D_LSTM_Attention --stim 1 --segment_number 3 --len_reduction None --isdebug False >> split-first-dependent.log
# python3 -u split-first-dependent-main-last.py --model_name Conv1D_LSTM_Attention --stim 0 --segment_number 5 --len_reduction None --isdebug False >> split-first-dependent.log
# python3 -u split-first-dependent-main-last.py --model_name Conv1D_LSTM_Attention --stim 1 --segment_number 5 --len_reduction None --isdebug False >> split-first-dependent.log
# python3 -u split-first-dependent-main-last.py --model_name Conv1D_LSTM_Attention --stim 0 --segment_number 60 --len_reduction None --isdebug False >> split-first-dependent.log
# python3 -u split-first-dependent-main-last.py --model_name Conv1D_LSTM_Attention --stim 1 --segment_number 60 --len_reduction None --isdebug False >> split-first-dependent.log
# python3 -u split-first-dependent-main-last.py --model_name CNN2D --stim 0 --segment_number 1 --len_reduction None --isdebug False >> split-first-dependent.log
# python3 -u split-first-dependent-main-last.py --model_name CNN2D --stim 1 --segment_number 1 --len_reduction None --isdebug False >> split-first-dependent.log
# python3 -u split-first-dependent-main-last.py --model_name CNN2D --stim 0 --segment_number 3 --len_reduction None --isdebug False >> split-first-dependent.log
# python3 -u split-first-dependent-main-last.py --model_name CNN2D --stim 1 --segment_number 3 --len_reduction None --isdebug False >> split-first-dependent.log
# python3 -u split-first-dependent-main-last.py --model_name CNN2D --stim 0 --segment_number 5 --len_reduction None --isdebug False >> split-first-dependent.log
# python3 -u split-first-dependent-main-last.py --model_name CNN2D --stim 1 --segment_number 5 --len_reduction None --isdebug False >> split-first-dependent.log
# python3 -u split-first-dependent-main-last.py --model_name CNN2D --stim 0 --segment_number 60 --len_reduction None --isdebug False >> split-first-dependent.log
# python3 -u split-first-dependent-main-last.py --model_name CNN2D --stim 1 --segment_number 60 --len_reduction None --isdebug False >> split-first-dependent.log
# python3 -u split-first-dependent-main-last.py --model_name Conv1D_LSTM_SelfAttention --stim 0 --segment_number 1 --len_reduction mean --isdebug False >> split-first-dependent.log
# python3 -u split-first-dependent-main-last.py --model_name Conv1D_LSTM_SelfAttention --stim 1 --segment_number 1 --len_reduction mean --isdebug False >> split-first-dependent.log
# python3 -u split-first-dependent-main-last.py --model_name Conv1D_LSTM_SelfAttention --stim 0 --segment_number 3 --len_reduction mean --isdebug False >> split-first-dependent.log
# python3 -u split-first-dependent-main-last.py --model_name Conv1D_LSTM_SelfAttention --stim 1 --segment_number 3 --len_reduction mean --isdebug False >> split-first-dependent.log
# python3 -u split-first-dependent-main-last.py --model_name Conv1D_LSTM_SelfAttention --stim 0 --segment_number 5 --len_reduction mean --isdebug False >> split-first-dependent.log
# python3 -u split-first-dependent-main-last.py --model_name Conv1D_LSTM_SelfAttention --stim 1 --segment_number 5 --len_reduction mean --isdebug False >> split-first-dependent.log
# python3 -u split-first-dependent-main-last.py --model_name Conv1D_LSTM_SelfAttention --stim 0 --segment_number 60 --len_reduction mean --isdebug False >> split-first-dependent.log
# python3 -u split-first-dependent-main-last.py --model_name Conv1D_LSTM_SelfAttention --stim 1 --segment_number 60 --len_reduction mean --isdebug False >> split-first-dependent.log


# python3 -u split-first-independent-main-last.py --model_name LSTM --stim 0 --segment_number 1 --len_reduction None --isdebug False >> split-first-independent.log
# python3 -u split-first-independent-main-last.py --model_name LSTM --stim 1 --segment_number 1 --len_reduction None --isdebug False >> split-first-independent.log
# python3 -u split-first-independent-main-last.py --model_name LSTM --stim 0 --segment_number 3 --len_reduction None --isdebug False >> split-first-independent.log
# python3 -u split-first-independent-main-last.py --model_name LSTM --stim 1 --segment_number 3 --len_reduction None --isdebug False >> split-first-independent.log
# python3 -u split-first-independent-main-last.py --model_name LSTM --stim 0 --segment_number 5 --len_reduction None --isdebug False >> split-first-independent.log
# python3 -u split-first-independent-main-last.py --model_name LSTM --stim 1 --segment_number 5 --len_reduction None --isdebug False >> split-first-independent.log
# python3 -u split-first-independent-main-last.py --model_name LSTM --stim 0 --segment_number 60 --len_reduction None --isdebug False >> split-first-independent.log
# python3 -u split-first-independent-main-last.py --model_name LSTM --stim 1 --segment_number 60 --len_reduction None --isdebug False >> split-first-independent.log
# python3 -u split-first-independent-main-last.py --model_name Conv1D_LSTM --stim 0 --segment_number 1 --len_reduction None --isdebug False >> split-first-independent.log
# python3 -u split-first-independent-main-last.py --model_name Conv1D_LSTM --stim 1 --segment_number 1 --len_reduction None --isdebug False >> split-first-independent.log
# python3 -u split-first-independent-main-last.py --model_name Conv1D_LSTM --stim 0 --segment_number 3 --len_reduction None --isdebug False >> split-first-independent.log
# python3 -u split-first-independent-main-last.py --model_name Conv1D_LSTM --stim 1 --segment_number 3 --len_reduction None --isdebug False >> split-first-independent.log
# python3 -u split-first-independent-main-last.py --model_name Conv1D_LSTM --stim 0 --segment_number 5 --len_reduction None --isdebug False >> split-first-independent.log
# python3 -u split-first-independent-main-last.py --model_name Conv1D_LSTM --stim 1 --segment_number 5 --len_reduction None --isdebug False >> split-first-independent.log
# python3 -u split-first-independent-main-last.py --model_name Conv1D_LSTM --stim 0 --segment_number 60 --len_reduction None --isdebug False >> split-first-independent.log
# python3 -u split-first-independent-main-last.py --model_name Conv1D_LSTM --stim 1 --segment_number 60 --len_reduction None --isdebug False >> split-first-independent.log
# python3 -u split-first-independent-main-last.py --model_name Conv1D_LSTM_Attention --stim 0 --segment_number 1 --len_reduction None --isdebug False >> split-first-independent.log
# python3 -u split-first-independent-main-last.py --model_name Conv1D_LSTM_Attention --stim 1 --segment_number 1 --len_reduction None --isdebug False >> split-first-independent.log
# python3 -u split-first-independent-main-last.py --model_name Conv1D_LSTM_Attention --stim 0 --segment_number 3 --len_reduction None --isdebug False >> split-first-independent.log
# python3 -u split-first-independent-main-last.py --model_name Conv1D_LSTM_Attention --stim 1 --segment_number 3 --len_reduction None --isdebug False >> split-first-independent.log
# python3 -u split-first-independent-main-last.py --model_name Conv1D_LSTM_Attention --stim 0 --segment_number 5 --len_reduction None --isdebug False >> split-first-independent.log
# python3 -u split-first-independent-main-last.py --model_name Conv1D_LSTM_Attention --stim 1 --segment_number 5 --len_reduction None --isdebug False >> split-first-independent.log
# python3 -u split-first-independent-main-last.py --model_name Conv1D_LSTM_Attention --stim 0 --segment_number 60 --len_reduction None --isdebug False >> split-first-independent.log
# python3 -u split-first-independent-main-last.py --model_name Conv1D_LSTM_Attention --stim 1 --segment_number 60 --len_reduction None --isdebug False >> split-first-independent.log
# python3 -u split-first-independent-main-last.py --model_name CNN2D --stim 0 --segment_number 1 --len_reduction None --isdebug False >> split-first-independent.log
# python3 -u split-first-independent-main-last.py --model_name CNN2D --stim 1 --segment_number 1 --len_reduction None --isdebug False >> split-first-independent.log
# python3 -u split-first-independent-main-last.py --model_name CNN2D --stim 0 --segment_number 3 --len_reduction None --isdebug False >> split-first-independent.log
# python3 -u split-first-independent-main-last.py --model_name CNN2D --stim 1 --segment_number 3 --len_reduction None --isdebug False >> split-first-independent.log
# python3 -u split-first-independent-main-last.py --model_name CNN2D --stim 0 --segment_number 5 --len_reduction None --isdebug False >> split-first-independent.log
# python3 -u split-first-independent-main-last.py --model_name CNN2D --stim 1 --segment_number 5 --len_reduction None --isdebug False >> split-first-independent.log
# python3 -u split-first-independent-main-last.py --model_name CNN2D --stim 0 --segment_number 60 --len_reduction None --isdebug False >> split-first-independent.log
# python3 -u split-first-independent-main-last.py --model_name CNN2D --stim 1 --segment_number 60 --len_reduction None --isdebug False >> split-first-independent.log
# python3 -u split-first-independent-main-last.py --model_name Conv1D_LSTM_SelfAttention --stim 0 --segment_number 1 --len_reduction mean --isdebug False >> split-first-independent.log
# python3 -u split-first-independent-main-last.py --model_name Conv1D_LSTM_SelfAttention --stim 1 --segment_number 1 --len_reduction mean --isdebug False >> split-first-independent.log
# python3 -u split-first-independent-main-last.py --model_name Conv1D_LSTM_SelfAttention --stim 0 --segment_number 3 --len_reduction mean --isdebug False >> split-first-independent.log
# python3 -u split-first-independent-main-last.py --model_name Conv1D_LSTM_SelfAttention --stim 1 --segment_number 3 --len_reduction mean --isdebug False >> split-first-independent.log
# python3 -u split-first-independent-main-last.py --model_name Conv1D_LSTM_SelfAttention --stim 0 --segment_number 5 --len_reduction mean --isdebug False >> split-first-independent.log
# python3 -u split-first-independent-main-last.py --model_name Conv1D_LSTM_SelfAttention --stim 1 --segment_number 5 --len_reduction mean --isdebug False >> split-first-independent.log
# python3 -u split-first-independent-main-last.py --model_name Conv1D_LSTM_SelfAttention --stim 0 --segment_number 60 --len_reduction mean --isdebug False >> split-first-independent.log
# python3 -u split-first-independent-main-last.py --model_name Conv1D_LSTM_SelfAttention --stim 1 --segment_number 60 --len_reduction mean --isdebug False >> split-first-independent.log


# python3 -u seg-first-independent-main-last.py --model_name LSTM --stim 0 --segment_number 1 --len_reduction None --isdebug False >> seg-first-independent.log
# python3 -u seg-first-independent-main-last.py --model_name LSTM --stim 1 --segment_number 1 --len_reduction None --isdebug False >> seg-first-independent.log
# python3 -u seg-first-independent-main-last.py --model_name LSTM --stim 0 --segment_number 3 --len_reduction None --isdebug False >> seg-first-independent.log
# python3 -u seg-first-independent-main-last.py --model_name LSTM --stim 1 --segment_number 3 --len_reduction None --isdebug False >> seg-first-independent.log
# python3 -u seg-first-independent-main-last.py --model_name LSTM --stim 0 --segment_number 5 --len_reduction None --isdebug False >> seg-first-independent.log
# python3 -u seg-first-independent-main-last.py --model_name LSTM --stim 1 --segment_number 5 --len_reduction None --isdebug False >> seg-first-independent.log
# python3 -u seg-first-independent-main-last.py --model_name LSTM --stim 0 --segment_number 60 --len_reduction None --isdebug False >> seg-first-independent.log
# python3 -u seg-first-independent-main-last.py --model_name LSTM --stim 1 --segment_number 60 --len_reduction None --isdebug False >> seg-first-independent.log
# python3 -u seg-first-independent-main-last.py --model_name Conv1D_LSTM --stim 0 --segment_number 1 --len_reduction None --isdebug False >> seg-first-independent.log
# python3 -u seg-first-independent-main-last.py --model_name Conv1D_LSTM --stim 1 --segment_number 1 --len_reduction None --isdebug False >> seg-first-independent.log
# python3 -u seg-first-independent-main-last.py --model_name Conv1D_LSTM --stim 0 --segment_number 3 --len_reduction None --isdebug False >> seg-first-independent.log
# python3 -u seg-first-independent-main-last.py --model_name Conv1D_LSTM --stim 1 --segment_number 3 --len_reduction None --isdebug False >> seg-first-independent.log
# python3 -u seg-first-independent-main-last.py --model_name Conv1D_LSTM --stim 0 --segment_number 5 --len_reduction None --isdebug False >> seg-first-independent.log
# python3 -u seg-first-independent-main-last.py --model_name Conv1D_LSTM --stim 1 --segment_number 5 --len_reduction None --isdebug False >> seg-first-independent.log
# python3 -u seg-first-independent-main-last.py --model_name Conv1D_LSTM --stim 0 --segment_number 60 --len_reduction None --isdebug False >> seg-first-independent.log
# python3 -u seg-first-independent-main-last.py --model_name Conv1D_LSTM --stim 1 --segment_number 60 --len_reduction None --isdebug False >> seg-first-independent.log
# python3 -u seg-first-independent-main-last.py --model_name Conv1D_LSTM_Attention --stim 0 --segment_number 1 --len_reduction None --isdebug False >> seg-first-independent.log
# python3 -u seg-first-independent-main-last.py --model_name Conv1D_LSTM_Attention --stim 1 --segment_number 1 --len_reduction None --isdebug False >> seg-first-independent.log
# python3 -u seg-first-independent-main-last.py --model_name Conv1D_LSTM_Attention --stim 0 --segment_number 3 --len_reduction None --isdebug False >> seg-first-independent.log
# python3 -u seg-first-independent-main-last.py --model_name Conv1D_LSTM_Attention --stim 1 --segment_number 3 --len_reduction None --isdebug False >> seg-first-independent.log
# python3 -u seg-first-independent-main-last.py --model_name Conv1D_LSTM_Attention --stim 0 --segment_number 5 --len_reduction None --isdebug False >> seg-first-independent.log
# python3 -u seg-first-independent-main-last.py --model_name Conv1D_LSTM_Attention --stim 1 --segment_number 5 --len_reduction None --isdebug False >> seg-first-independent.log
# python3 -u seg-first-independent-main-last.py --model_name Conv1D_LSTM_Attention --stim 0 --segment_number 60 --len_reduction None --isdebug False >> seg-first-independent.log
# python3 -u seg-first-independent-main-last.py --model_name Conv1D_LSTM_Attention --stim 1 --segment_number 60 --len_reduction None --isdebug False >> seg-first-independent.log
# python3 -u seg-first-independent-main-last.py --model_name CNN2D --stim 0 --segment_number 1 --len_reduction None --isdebug False >> seg-first-independent.log
# python3 -u seg-first-independent-main-last.py --model_name CNN2D --stim 1 --segment_number 1 --len_reduction None --isdebug False >> seg-first-independent.log
# python3 -u seg-first-independent-main-last.py --model_name CNN2D --stim 0 --segment_number 3 --len_reduction None --isdebug False >> seg-first-independent.log
# python3 -u seg-first-independent-main-last.py --model_name CNN2D --stim 1 --segment_number 3 --len_reduction None --isdebug False >> seg-first-independent.log
# python3 -u seg-first-independent-main-last.py --model_name CNN2D --stim 0 --segment_number 5 --len_reduction None --isdebug False >> seg-first-independent.log
# python3 -u seg-first-independent-main-last.py --model_name CNN2D --stim 1 --segment_number 5 --len_reduction None --isdebug False >> seg-first-independent.log
# python3 -u seg-first-independent-main-last.py --model_name CNN2D --stim 0 --segment_number 60 --len_reduction None --isdebug False >> seg-first-independent.log
# python3 -u seg-first-independent-main-last.py --model_name CNN2D --stim 1 --segment_number 60 --len_reduction None --isdebug False >> seg-first-independent.log
# python3 -u seg-first-independent-main-last.py --model_name Conv1D_LSTM_SelfAttention --stim 0 --segment_number 1 --len_reduction mean --isdebug False >> seg-first-independent.log
# python3 -u seg-first-independent-main-last.py --model_name Conv1D_LSTM_SelfAttention --stim 1 --segment_number 1 --len_reduction mean --isdebug False >> seg-first-independent.log
# python3 -u seg-first-independent-main-last.py --model_name Conv1D_LSTM_SelfAttention --stim 0 --segment_number 3 --len_reduction mean --isdebug False >> seg-first-independent.log
# python3 -u seg-first-independent-main-last.py --model_name Conv1D_LSTM_SelfAttention --stim 1 --segment_number 3 --len_reduction mean --isdebug False >> seg-first-independent.log
# python3 -u seg-first-independent-main-last.py --model_name Conv1D_LSTM_SelfAttention --stim 0 --segment_number 5 --len_reduction mean --isdebug False >> seg-first-independent.log
# python3 -u seg-first-independent-main-last.py --model_name Conv1D_LSTM_SelfAttention --stim 1 --segment_number 5 --len_reduction mean --isdebug False >> seg-first-independent.log
# python3 -u seg-first-independent-main-last.py --model_name Conv1D_LSTM_SelfAttention --stim 0 --segment_number 60 --len_reduction mean --isdebug False >> seg-first-independent.log
# python3 -u seg-first-independent-main-last.py --model_name Conv1D_LSTM_SelfAttention --stim 1 --segment_number 60 --len_reduction mean --isdebug False >> seg-first-independent.log


# python3 -u seg-first-dependent-main-last.py --model_name LSTM --stim 0 --segment_number 1 --len_reduction None --isdebug False >> seg-first-dependent.log
# python3 -u seg-first-dependent-main-last.py --model_name LSTM --stim 1 --segment_number 1 --len_reduction None --isdebug False >> seg-first-dependent.log
# python3 -u seg-first-dependent-main-last.py --model_name LSTM --stim 0 --segment_number 3 --len_reduction None --isdebug False >> seg-first-dependent.log
# python3 -u seg-first-dependent-main-last.py --model_name LSTM --stim 1 --segment_number 3 --len_reduction None --isdebug False >> seg-first-dependent.log
# python3 -u seg-first-dependent-main-last.py --model_name LSTM --stim 0 --segment_number 5 --len_reduction None --isdebug False >> seg-first-dependent.log
# python3 -u seg-first-dependent-main-last.py --model_name LSTM --stim 1 --segment_number 5 --len_reduction None --isdebug False >> seg-first-dependent.log
# python3 -u seg-first-dependent-main-last.py --model_name LSTM --stim 0 --segment_number 60 --len_reduction None --isdebug False >> seg-first-dependent.log
# python3 -u seg-first-dependent-main-last.py --model_name LSTM --stim 1 --segment_number 60 --len_reduction None --isdebug False >> seg-first-dependent.log
# python3 -u seg-first-dependent-main-last.py --model_name Conv1D_LSTM --stim 0 --segment_number 1 --len_reduction None --isdebug False >> seg-first-dependent.log
# python3 -u seg-first-dependent-main-last.py --model_name Conv1D_LSTM --stim 1 --segment_number 1 --len_reduction None --isdebug False >> seg-first-dependent.log
# python3 -u seg-first-dependent-main-last.py --model_name Conv1D_LSTM --stim 0 --segment_number 3 --len_reduction None --isdebug False >> seg-first-dependent.log
# python3 -u seg-first-dependent-main-last.py --model_name Conv1D_LSTM --stim 1 --segment_number 3 --len_reduction None --isdebug False >> seg-first-dependent.log
# python3 -u seg-first-dependent-main-last.py --model_name Conv1D_LSTM --stim 0 --segment_number 5 --len_reduction None --isdebug False >> seg-first-dependent.log
# python3 -u seg-first-dependent-main-last.py --model_name Conv1D_LSTM --stim 1 --segment_number 5 --len_reduction None --isdebug False >> seg-first-dependent.log
# python3 -u seg-first-dependent-main-last.py --model_name Conv1D_LSTM --stim 0 --segment_number 60 --len_reduction None --isdebug False >> seg-first-dependent.log
# python3 -u seg-first-dependent-main-last.py --model_name Conv1D_LSTM --stim 1 --segment_number 60 --len_reduction None --isdebug False >> seg-first-dependent.log
# python3 -u seg-first-dependent-main-last.py --model_name Conv1D_LSTM_Attention --stim 0 --segment_number 1 --len_reduction None --isdebug False >> seg-first-dependent.log
# python3 -u seg-first-dependent-main-last.py --model_name Conv1D_LSTM_Attention --stim 1 --segment_number 1 --len_reduction None --isdebug False >> seg-first-dependent.log
# python3 -u seg-first-dependent-main-last.py --model_name Conv1D_LSTM_Attention --stim 0 --segment_number 3 --len_reduction None --isdebug False >> seg-first-dependent.log
# python3 -u seg-first-dependent-main-last.py --model_name Conv1D_LSTM_Attention --stim 1 --segment_number 3 --len_reduction None --isdebug False >> seg-first-dependent.log
# python3 -u seg-first-dependent-main-last.py --model_name Conv1D_LSTM_Attention --stim 0 --segment_number 5 --len_reduction None --isdebug False >> seg-first-dependent.log
# python3 -u seg-first-dependent-main-last.py --model_name Conv1D_LSTM_Attention --stim 1 --segment_number 5 --len_reduction None --isdebug False >> seg-first-dependent.log
# python3 -u seg-first-dependent-main-last.py --model_name Conv1D_LSTM_Attention --stim 0 --segment_number 60 --len_reduction None --isdebug False >> seg-first-dependent.log
# python3 -u seg-first-dependent-main-last.py --model_name Conv1D_LSTM_Attention --stim 1 --segment_number 60 --len_reduction None --isdebug False >> seg-first-dependent.log
# python3 -u seg-first-dependent-main-last.py --model_name CNN2D --stim 0 --segment_number 1 --len_reduction None --isdebug False >> seg-first-dependent.log
# python3 -u seg-first-dependent-main-last.py --model_name CNN2D --stim 1 --segment_number 1 --len_reduction None --isdebug False >> seg-first-dependent.log
# python3 -u seg-first-dependent-main-last.py --model_name CNN2D --stim 0 --segment_number 3 --len_reduction None --isdebug False >> seg-first-dependent.log
# python3 -u seg-first-dependent-main-last.py --model_name CNN2D --stim 1 --segment_number 3 --len_reduction None --isdebug False >> seg-first-dependent.log
# python3 -u seg-first-dependent-main-last.py --model_name CNN2D --stim 0 --segment_number 5 --len_reduction None --isdebug False >> seg-first-dependent.log
# python3 -u seg-first-dependent-main-last.py --model_name CNN2D --stim 1 --segment_number 5 --len_reduction None --isdebug False >> seg-first-dependent.log
# python3 -u seg-first-dependent-main-last.py --model_name CNN2D --stim 0 --segment_number 60 --len_reduction None --isdebug False >> seg-first-dependent.log
# python3 -u seg-first-dependent-main-last.py --model_name CNN2D --stim 1 --segment_number 60 --len_reduction None --isdebug False >> seg-first-dependent.log
# python3 -u seg-first-dependent-main-last.py --model_name Conv1D_LSTM_SelfAttention --stim 0 --segment_number 1 --len_reduction mean --isdebug False >> seg-first-dependent.log
# python3 -u seg-first-dependent-main-last.py --model_name Conv1D_LSTM_SelfAttention --stim 1 --segment_number 1 --len_reduction mean --isdebug False >> seg-first-dependent.log
# python3 -u seg-first-dependent-main-last.py --model_name Conv1D_LSTM_SelfAttention --stim 0 --segment_number 3 --len_reduction mean --isdebug False >> seg-first-dependent.log
# python3 -u seg-first-dependent-main-last.py --model_name Conv1D_LSTM_SelfAttention --stim 1 --segment_number 3 --len_reduction mean --isdebug False >> seg-first-dependent.log
# python3 -u seg-first-dependent-main-last.py --model_name Conv1D_LSTM_SelfAttention --stim 0 --segment_number 5 --len_reduction mean --isdebug False >> seg-first-dependent.log
# python3 -u seg-first-dependent-main-last.py --model_name Conv1D_LSTM_SelfAttention --stim 1 --segment_number 5 --len_reduction mean --isdebug False >> seg-first-dependent.log
# python3 -u seg-first-dependent-main-last.py --model_name Conv1D_LSTM_SelfAttention --stim 0 --segment_number 60 --len_reduction mean --isdebug False >> seg-first-dependent.log
# python3 -u seg-first-dependent-main-last.py --model_name Conv1D_LSTM_SelfAttention --stim 1 --segment_number 60 --len_reduction mean --isdebug False >> seg-first-dependent.log
